In [32]:
import numpy as np
import pandas as pd
from keras import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [33]:
df = pd.read_csv('vector.csv', sep=',')
data = df.to_numpy()
x = data[:, 1:].astype('float')
y = data[:, 0]

In [34]:
label_encoder = LabelEncoder()
y_int = label_encoder.fit_transform(y)
y_onehot = OneHotEncoder(sparse=False)
y_int = y_int.reshape(len(y_int), 1)
y_onehot = y_onehot.fit_transform(y_int)
x_train, x_test, y_train, y_test = train_test_split(x, y_onehot, test_size=0.3)

In [35]:
model = Sequential()
model.add(Dense(10, input_dim=6, activation='sigmoid'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 10)                70        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 33        
Total params: 103
Trainable params: 103
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.fit(x_train, y_train, epochs=200, batch_size=10, shuffle=True)

Epoch 1/200
2/2 [==============================] - 0s 498us/step - loss: 1.2816 - accuracy: 0.3500
Epoch 2/200
2/2 [==============================] - 0s 506us/step - loss: 1.2618 - accuracy: 0.3500
Epoch 3/200
2/2 [==============================] - 0s 1ms/step - loss: 1.2507 - accuracy: 0.3500
Epoch 4/200
2/2 [==============================] - 0s 499us/step - loss: 1.2369 - accuracy: 0.3500
Epoch 5/200
2/2 [==============================] - 0s 997us/step - loss: 1.2269 - accuracy: 0.3500
Epoch 6/200
2/2 [==============================] - 0s 498us/step - loss: 1.2152 - accuracy: 0.3500
Epoch 7/200
2/2 [==============================] - 0s 1ms/step - loss: 1.2059 - accuracy: 0.3500
Epoch 8/200
2/2 [==============================] - 0s 1ms/step - loss: 1.1940 - accuracy: 0.3500
Epoch 9/200
2/2 [==============================] - 0s 499us/step - loss: 1.1857 - accuracy: 0.3500
Epoch 10/200
2/2 [==============================] - 0s 498us/step - loss: 1.1802 - accuracy: 0.3500
Epoch 11/200
2/

2/2 [==============================] - 0s 498us/step - loss: 0.9325 - accuracy: 0.7000
Epoch 84/200
2/2 [==============================] - 0s 1000us/step - loss: 0.9329 - accuracy: 0.7000
Epoch 85/200
2/2 [==============================] - 0s 1ms/step - loss: 0.9317 - accuracy: 0.7000
Epoch 86/200
2/2 [==============================] - 0s 503us/step - loss: 0.9330 - accuracy: 0.7000
Epoch 87/200
2/2 [==============================] - 0s 501us/step - loss: 0.9306 - accuracy: 0.7000
Epoch 88/200
2/2 [==============================] - 0s 1ms/step - loss: 0.9302 - accuracy: 0.7000
Epoch 89/200
2/2 [==============================] - 0s 500us/step - loss: 0.9333 - accuracy: 0.7000
Epoch 90/200
2/2 [==============================] - 0s 1ms/step - loss: 0.9278 - accuracy: 0.7000
Epoch 91/200
2/2 [==============================] - 0s 500us/step - loss: 0.9283 - accuracy: 0.7000
Epoch 92/200
2/2 [==============================] - 0s 1ms/step - loss: 0.9273 - accuracy: 0.7000
Epoch 93/200
2/2 [==

2/2 [==============================] - 0s 1ms/step - loss: 0.8858 - accuracy: 0.7000
Epoch 165/200
2/2 [==============================] - 0s 500us/step - loss: 0.8821 - accuracy: 0.7000
Epoch 166/200
2/2 [==============================] - 0s 1000us/step - loss: 0.8845 - accuracy: 0.7000
Epoch 167/200
2/2 [==============================] - 0s 500us/step - loss: 0.8817 - accuracy: 0.7000
Epoch 168/200
2/2 [==============================] - 0s 501us/step - loss: 0.8886 - accuracy: 0.7000
Epoch 169/200
2/2 [==============================] - 0s 499us/step - loss: 0.8805 - accuracy: 0.7000
Epoch 170/200
2/2 [==============================] - 0s 501us/step - loss: 0.8798 - accuracy: 0.7000
Epoch 171/200
2/2 [==============================] - 0s 1ms/step - loss: 0.8807 - accuracy: 0.7000
Epoch 172/200
2/2 [==============================] - 0s 499us/step - loss: 0.8778 - accuracy: 0.7000
Epoch 173/200
2/2 [==============================] - 0s 501us/step - loss: 0.8779 - accuracy: 0.7000
Epoch 1

In [37]:
y_pred = model.predict(x_test)
y_pred_int = np.argmax(y_pred, axis=1)
y_test_int = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test_int, y_pred_int)
print(cm)

[[2 0 0]
 [0 3 0]
 [0 4 0]]
